import re
if(__name__=='__main__'):

    a="able    abominable  acceptable  accessible  accountable\
    achievable  actionable  adaptable   addle   addressable\
    adjustable  admirable   admissible  adorable    advisable\
    affable affordable  agile   agreeable   aisle\
    ale allele  allocatable allowable   alterable\
    amble   amenable    amendable   amiable amicable\
    ample   analysable  angle   ankle   answerable\
    apostle apple   applicable  appreciable approachable\
    arable  arguable    armhole arrangeable arrestable\
    article ascertainable   ascribable  assailable  assemble\
    assessable  assignable  assimilable astraddle   attachable\
    attainable  attributable    audible automobile  available\
    avoidable   awhile  axle    babble  baffle\
    bagatelle   bale    bamboozle   bangle  bankable\
    bargepole   barnacle    battle  bauble  beadle\
    beagle  beanpole    bearable    beetle  befuddle\
    beguile believable  belittle    belle   bible\
    bibliophile bicycle bile    billable    binnacle\
    biodegradable   bistable    blameable   bluebottle  bobble\
    boggle  bolt-hole   bookable    borehole    borrowable\
    bottle  bramble breakable   breathable  bridle\
    bristle brittle bubble  buckle  bugle\
    bumble  bundle  bungle  burble  burgle\
    bustle  buttonhole  cable   cackle  cagoule\
    cajole  calculable  callable    camisole    camomile\
    campanile   candle  canticle    capable capsule\
    carbuncle   casserole   castle  cattle  certifiable\
    chamomile   changeable  chargeable  charitable  chewable\
    chorale chortle chronicle   chuckle circle\
    circumventable  claimable   classifiable    clavicle    clientele\
    climbable   closable    cobble  cockle  coddle\
    coercible   collapsible collectable combustible comestible\
    comfortable commendable communicable    companionable   comparable\
    compatible  compilable  compile completable comprehensible\
    compressible    computable  conceivable condemnable condole\
    condonable  configurable    conformable confusable  conquerable\
    conscionable    considerable    console constable   constructable\
    consumable  contactable containable contemptible    contestable\
    continuable contractible    contractile controllable    conventicle\
    convertible copyable    copyrightable   coracle corpuscle\
    correctable corruptible countable   counterexample  couple\
    crab-apple  crackable   crackle cradle  craftspeople\
    creatable   credible    creditable  creole  crinkle\
    cripple crocodile   crucible    crucifiable crumble\
    crumple cubicle cuddle  culpable    cultivable\
    curable curdle  curricle    customisable    customizable\
    cuticle cuttle  cycle   dabble  dale\
    damnable    danceable   dangle  dapple  datable\
    dawdle  dazzle  debacle debatable   decidable\
    decipherable    decomposable    decouple    deducible   deductible\
    defensible  defile  definable   deflatable  deformable\
    degradable  delectable  deletable   deliverable demonstrable\
    demountable dependable  deplorable  derivable   describable\
    designable  desirable   despicable  destroyable detachable\
    detectable  determinable    detestable  diagnosable differentiable\
    digestible  diminishable    dimple  dipole  dirigible\
    disable disagreeable    disassemble discernible disciple\
    discountable    discoverable    discreditable   discussable disentangle\
    dishonourable   dismantle   dismissible dispensable displayable\
    disposable  disprovable disputable  disreputable    dissemble\
    distinguishable distributable   disyllable  divisible   docile\
    dole    domicile    doodle  double  drawable\
    dribble drinkable   drivable    drizzle ductile\
    dung-beetle durable dwindle eagle   eatable\
    edible  editable    electable   eligible    embeddable\
    embezzle    employable  enable  encircle    endurable\
    enfeeble    enforceable enhanceable enjoyable   ennoble\
    ensemble    entangle    entitle enumerable  enviable\
    epistle equable equitable   erasable    erectile\
    erstwhile   estimable   evadable    evaluable   examinable\
    example exceptionable   exchangeable    excitable   excusable\
    execrable   executable  exercisable exhale  exhaustible\
    exile   expandable  expansible  expendable  explainable\
    explicable  exploitable explorable  exportable  expressible\
    extendable  extendible  extensible  extractable extraditable\
    fable   facile  facsimile   factorisable    fairytale\
    fallible    falsifiable fanciable   fashionable favourable\
    feasible    febrile feeble  female  ferrule\
    fertile fettle  fickle  fiddle  file\
    finale  findable    fissile fixable fizzle\
    flagpole    flammable   flexible    flippable   foible\
    follicle    followable  fondle  forcible    foreseeable\
    forgettable forgivable  formidable  foxhole fragile\
    frazzle freestyle   friable frizzle full-scale\
    fumarole    fumble  fusible futile  gabble\
    gable   gaggle  gale    gamble  garble\
    gargle  gargoyle    gas-permeable   gazelle generalisable\
    generalizable   gentile gentle  gettable    giggle\
    girdle  globule gobble  granule grapple\
    graticule   great-uncle grille  gristle grumble\
    guacamole   guessable   guile   gullible    gunwale\
    gurgle  guzzle  habitable   hackable    haggle\
    hairstyle   hale    handle  hassle  heckle\
    hell-hole   heritable   high-profile    hittable    hobble\
    holdable    hole    honeysuckle honourable  horrible\
    hospitable  hostile huddle  humble  hummable\
    hurdle  hurtle  hustle  hyperbole   icicle\
    identifiable    idle    ignoble ignorable   illegible\
    illimitable imaginable  imbecile    immeasurable    immiscible\
    immobile    immovable   immoveable  immutable   impale\
    impalpable  impassable  impeccable  impenetrable    imperceptible\
    imperishable    impermeable impermissible   imperturbable   implacable\
    implausible implementable   imponderable    importable  imposable\
    impossible  impracticable   impregnable impressionable  improbable\
    improvable  impugnable  inaccessible    inadmissible    inadvisable\
    inalienable inapplicable    inaudible   incalculable    incapable\
    incombustible   incommensurable incommunicable  incomparable    incompatible\
    incomprehensible    incompressible  inconceivable   inconsiderable  inconsolable\
    incontestable   incontrovertible    incorporable    incorrigible    incorruptible\
    incredible  incurable   indecipherable  indeclinable    indefatigable\
    indefeasible    indefensible    indefinable indelible   indescribable\
    indestructible  indeterminable  indictable  indigestible    indispensable\
    indisputable    indissoluble    indistinguishable   indivisible indomitable\
    indubitable inducible   inedible    ineffable   ineligible\
    ineluctable inequitable ineradicable    inescapable inestimable\
    inevitable  inexcusable inexhaustible   inexorable  inexplicable\
    inexpressible   inextensible    inextinguishable    inextricable    infallible\
    infantile   infeasible  infertile   inflammable inflatable\
    inflexible  inhabitable inhale  inheritable inhospitable\
    inimitable  injectable  innumerable inoperable  insatiable\
    inscrutable insensible  inseparable insole  insoluble\
    installable insufferable    insuperable insupportable   insurmountable\
    intangible  integrable  intelligible    interchangeable interminable\
    interoperable   interpolatable  interpretable   intolerable intractable\
    invaluable  invariable  inveigle    invertible  invincible\
    inviolable  invisible   invokable   invulnerable    irascible\
    irreconcilable  irrecoverable   irredeemable    irreducible irrefutable\
    irremediable    irremovable irreparable irreplaceable   irrepressible\
    irreproachable  irresistible    irresolvable    irresponsible   irretrievable\
    irreversible    irrevocable irritable   isle    issuable\
    jangle  jingle  jostle  joule   juggle\
    jumble  jungle  justifiable juvenile    kale\
    kettle  keyhole kindle  knowable    knowledgeable\
    knuckle kyle    labile  ladle   lamentable\
    large-scale laudable    laughable   learnable   legible\
    liable  lifestyle   likable likeable    linkable\
    little  loadable    loanable    locale  locatable\
    lockable    loophole    losable lovable loveable\
    low-profile machine-readable    mademoiselle    mailable    maintainable\
    male    malleable   manacle manageable  manciple\
    mandible    mangle  manhandle   manhole manipulable\
    manoeuvrable    mantle  maple   mappable    marble\
    marketable  marriageable    martingale  matchable   maypole\
    meanwhile   measurable  mechanisable    mechanizable    meddle\
    memorable   mentionable mercantile  merchantable    metastable\
    mettle  microwaveable   middle  mile    mingle\
    minuscule   miracle miscible    miserable   mishandle\
    misrule missile mobile  mobilisable mobilizable\
    modifiable  module  mole    molecule    monocle\
    monopole    monostable  monosyllable    morale  mortgageable\
    motile  motorcycle  mountable   movable moveable\
    muddle  muffle  mule    multiple    mumble\
    muscle  mutable muzzle  nameable    navigable\
    needle  negligible  negotiable  nestable    nestle\
    nettle  new-style   nibble  niggle  nightingale\
    nimble  nipple  noble   noddle  nodule\
    non-negotiable  non-returnable  non-transferable    noodle  normalisable\
    normalizable    notable noticeable  notifiable  nozzle\
    nubile  nuzzle  objectionable   observable  obstacle\
    obtainable  ogle    oil-shale   old-style   operable\
    oracle  organisable orientable  ostensible  overrule\
    packable    paddle  paedophile  palatable   pale\
    palpable    pantile parable pardonable  parole\
    participle  particle    passable    passenger-mile  pastille\
    patchable   patentable  payable peaceable   pebble\
    peddle  peephole    penetrable  penile  pensionable\
    people  perceivable percentile  perceptible performable\
    perishable  permeable   permissible personable  pestle\
    pickle  piffle  pigeon-hole pile    pimple\
    pineapple   pinnacle    pitiable    plausible   playable\
    pleasurable pliable plughole    point-of-sale   pole\
    polysyllable    poodle  portable    porthole    positionable\
    possible    potable pothole pourable    practicable\
    prattle preamble    predictable preferable  prehensile\
    presentable presumable  preventable prickle principle\
    printable   probable    processable procurable  producible\
    profile profitable  programmable    projectile  promotable\
    pronounceable   prosecutable    provable    providable  publishable\
    puddle  puerile punchable   punishable  purchasable\
    purple  pushable    pustule puzzle  quadrangle\
    quadrille   quadruple   quadrupole  quantifiable    quartile\
    questionable    quibble quintuple   quotable    rabble\
    raffle  ramble  ramshackle  rankle  ratable\
    ratatouille rateable    rationale   rattle  reachable\
    readable    realisable  realizable  reasonable  reassemble\
    rebuttable  receivable  receptacle  rechargeable    reclaimable\
    recognisable    recognizable    recommendable   recompile   recomputable\
    reconcilable    reconcile   reconfigurable  recordable  recouple\
    recoverable rectangle   rectifiable recyclable  recycle\
    redeemable  redistributable redouble    redoubtable reducible\
    referable   refile  refillable  reformable  refreshable\
    refundable  refutable   regale  registrable regrettable\
    rekindle    releasable  reliable    relocatable remarkable\
    remediable  removable   renewable   repairable  repayable\
    repeatable  replaceable replicable  reportable  reprehensible\
    representable   reproducible    reprogrammable  reptile reputable\
    resale  rescale reschedule  resemble    resettable\
    resettle    reshuffle   resistible  resolvable  respectable\
    responsible restartable reticule    retractable retrievable\
    returnable  reusable    revealable  reveille    reversible\
    reviewable  revile  revisable   revocable   rewindable\
    rewritable  riddle  ridicule    rifle   rigmarole\
    rile    ripple  risible rissole role\
    rotatable   rouble  rubble  ruffle  rule\
    rumble  rumple  runnable    rustle  sable\
    saddle  sale    saleable    salespeople salvageable\
    sample  sandcastle  satisfiable scalable    scale\
    schedule    scrabble    scramble    scribble    scrollable\
    scruple scuffle scuttle seasonable  selectable\
    semicircle  senile  sensible    separable   serviceable\
    servile sessile settable    settle  severable\
    shackle shakable    shakeable   shale   shamble\
    sharable    shareable   shingle shippable   shrinkable\
    shuffle shuttle sickle  side-saddle sidle\
    simile  simple  singable    single  sinkable\
    sizable sizeable    sizzle  skittle small-scale\
    smellable   smile   smuggle snaffle sniffle\
    snuffle snuggle sociable    sole    soluble\
    solvable    sortable    souffle spangle sparkle\
    speakable   specifiable speckle spectacle   spellable\
    spindle spittle splittable  spokespeople    sprinkle\
    spyhole squabble    squiggle    stable  stale\
    staple  startle steeple steerable   sterile\
    stifle  stile   stockpile   stole   stoppable\
    straddle    straggle    strangle    stretchable struggle\
    stubble stumble style   submersible submittable\
    substitutable   subtitle    subtle  suckable    suckle\
    suggestible suitable    summable    supple  supportable\
    suppressible    surmountable    survivable  susceptible sustainable\
    swappable   sweepable   swindle switchable  syllable\
    tabernacle  table   tackle  tactile tadpole\
    tailorable  takeable    tale    tangible    tangle\
    tattle  tax-deductible  taxable teachable   tell-tale\
    temple  tenable tensile tentacle    terrible\
    testable    testicle    textile thermocouple    thermophile\
    thimble thinkable   thistle throttle    tickle\
    tile    timescale   timetable   tingle  tinkle\
    tipple  title   tittle-tattle   toddle  toggle\
    tolerable   tootle  topple  townspeople traceable\
    tractable   tradeable   tradespeople    trample transferable\
    translatable    transmissible   transmittable   transportable   trappable\
    treacle treadle treasonable treatable   treble\
    tremble trestle triangle    tribespeople    trickle\
    tricycle    trifle  triple  trouble truffle\
    trundle tumble  tunable turnstile   turntable\
    turtle  tussle  twiddle twinkle ukulele\
    unable  unacceptable    unaccountable   unachievable    unaddressable\
    unaffordable    unalterable unanswerable    unapproachable  unarguable\
    unassailable    unattainable    unattributable  unavailable unavoidable\
    unbearable  unbeatable  unbelievable    unbreakable unbridgeable\
    unbuckle    unchallengeable unchangeable    uncharitable    uncheckable\
    unclassifiable  uncle   unclimbable uncomfortable   uncompilable\
    uncompromisable unconquerable   unconscionable  uncontainable   uncontrollable\
    uncorrectable   uncountable uncouple    uncrackable uncrossable\
    uncrushable undecidable undefinable undeliverable   undeniable\
    understandable  undesirable undetectable    undiagnosable   undrinkable\
    undroppable uneatable   unelectable unemployable    unendurable\
    unenforceable   unenviable  unexceptionable unexplainable   unfalsifiable\
    unfashionable   unfathomable    unfavourable    unfeasible  unfetchable\
    unfordable  unforeseeable   unforgettable   unforgivable    unfulfillable\
    ungovernable    unguessable unicycle    unidentifiable  unifiable\
    unimaginable    unimpeachable   unimplementable uninhabitable   uninsurable\
    unintelligible  uninterpretable unjustifiable   unknowable  unlikeable\
    unlovable   unmaintainable  unmanageable    unmatchable unmeasurable\
    unmeetable  unmemorable unmentionable   unmissable  unmistakable\
    unmistakeable   unmodifiable    unnavigable unnoticeable    unobjectionable\
    unobservable    unobtainable    unpalatable unpardonable    unplayable\
    unportable  unpredictable   unprintable unprofitable    unpronounceable\
    unprovable  unpublishable   unquantifiable  unquenchable    unquestionable\
    unraisable  unreachable unreadable  unrealisable    unrealizable\
    unreasonable    unrecognisable  unrecognizable  unrecoverable   unreleasable\
    unreliable  unremarkable    unrepairable    unrepeatable    unrepresentable\
    unreproducible  unresolvable    unriddle    unsaleable  unsatisfiable\
    unscramble  unsealable  unseasonable    unsellable  unserviceable\
    unsettle    unshakable  unshakeable unsharable  unshockable\
    unsinkable  unsociable  unsolvable  unspeakable unstable\
    unstoppable unstretchable   unsubtle    unsuitable  unsupportable\
    unsurpassable   unsurvivable    unsustainable   unswappable untangle\
    untenable   untestable  unthinkable untouchable untraceable\
    untranslatable  untransportable untrappable untreatable unusable\
    unutterable unverifiable    unvisitable unwarrantable   unwatchable\
    unwindable  unworkable  upgradable  upgradeable usable\
    useable vacuole vale    valuable    variable\
    vegetable   vehicle venerable   ventricle   verifiable\
    veritable   versatile   versicle    vesicle vestibule\
    viable  viewable    vile    virile  visible\
    visitable   voidable    voile   volatile    vole\
    voluble vulnerable  waddle  waffle  waggle\
    walkable    warble  washable    watchable   water-soluble\
    water-table waterhole   wattle  wearable    wettable\
    whale   wheedle while   whistle whittle\
    whole   wholesale   wide-angle  wiggle  wile\
    wimple  winkle  winnable    wobble  woodpile\
    work-to-rule    workable    workpeople  wormhole    worthwhile\
    wrangle wrestle wriggle wrinkle writable"

    r=re.compile('\s')
    ablep=re.compile('able$')
    b=r.split(a)
    for elem in b:
        if(elem != '' and None!=ablep.search(elem)):
            print(" "+ablep.sub('',elem))
